In [3]:
import numpy as np

data = np.loadtxt('D:/2023_jsm_r/jupyter_2023_j/data/chocolate_rating.csv',delimiter = ',' )

print('차원:', data.ndim,'\n')

print('모양:', data.shape,'\n')

print('원소 수 : ', data.size,'\n')

print(data)

차원: 2 

모양: (1795, 4) 

원소 수 :  7180 

[[1.000e+00 2.016e+03 6.300e-01 3.750e+00]
 [2.000e+00 2.015e+03 7.000e-01 2.750e+00]
 [3.000e+00 2.015e+03 7.000e-01 3.000e+00]
 ...
 [1.793e+03 2.011e+03 6.500e-01 3.500e+00]
 [1.794e+03 2.011e+03 6.200e-01 3.250e+00]
 [1.795e+03 2.010e+03 6.500e-01 3.000e+00]]


In [6]:
# 모든 초콜릿의 평균 평점

ratings_mean = data[:,3]. mean()    ##  넘파이에서는 : 이 모든을 뜻함. 
print(ratings_mean)



3.185933147632312


In [15]:
# 평점이 4 이상인 우수 초콜릿을 high_level 변수로 저장

high_level = data [ data[:,3]>=4]
   
print(high_level)




[[1.000e+01 2.014e+03 7.000e-01 4.000e+00]
 [1.800e+01 2.013e+03 7.000e-01 4.000e+00]
 [2.100e+01 2.013e+03 6.300e-01 4.000e+00]
 [5.500e+01 2.011e+03 7.000e-01 4.000e+00]
 [5.700e+01 2.010e+03 7.000e-01 4.000e+00]
 [7.700e+01 2.007e+03 7.000e-01 4.000e+00]
 [7.800e+01 2.007e+03 7.500e-01 4.000e+00]
 [7.900e+01 2.007e+03 7.000e-01 5.000e+00]
 [8.400e+01 2.007e+03 7.000e-01 4.000e+00]
 [8.700e+01 2.006e+03 7.000e-01 5.000e+00]
 [8.800e+01 2.006e+03 6.600e-01 4.000e+00]
 [9.300e+01 2.010e+03 6.000e-01 4.000e+00]
 [1.080e+02 2.016e+03 7.000e-01 4.000e+00]
 [1.090e+02 2.016e+03 7.000e-01 4.000e+00]
 [1.180e+02 2.015e+03 7.000e-01 4.000e+00]
 [1.240e+02 2.011e+03 7.200e-01 4.000e+00]
 [1.530e+02 2.014e+03 7.000e-01 4.000e+00]
 [1.800e+02 2.013e+03 7.300e-01 4.000e+00]
 [1.810e+02 2.011e+03 7.200e-01 4.000e+00]
 [1.870e+02 2.011e+03 7.200e-01 4.000e+00]
 [2.230e+02 2.014e+03 7.500e-01 4.000e+00]
 [2.320e+02 2.011e+03 7.500e-01 4.000e+00]
 [2.330e+02 2.011e+03 7.500e-01 4.000e+00]
 [2.400e+02

In [18]:
# 우수초콜릿(high_level)의 번호를 정수로 변환해서 high_id 변수로 저장 

high_id = high_level[:,0].astype(np.int64)   # 0번 인덱스 타입을 정수형으로 변환해서 우수 초콜릿의 개수
print(high_id)

print('\n우수  초콜릿 개수 : ', high_id.size)


[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394 1426 1428 1433 1479 1488 1513 1516
 1529 1530 1531 1533 1536 1537 1544 1545 1664 1683 1686 1688 1694 1700
 1740 1757]

우수  초콜릿 개수 :  100
