In [20]:
import numpy as np

# 리스트를 생성하고 배열로 변환하기

list1 = [1,2,3,4]
a = np.array(list1)

print('a.shape:', a.shape)
print('a[0]:', a[0],"\n")

# 2차원 배열 생성하기 
b = np.array([[1,2,3],[4,5,6]])

print('b.shape:', b.shape)
print('b[0,0]:',b[0,0])
print('b[0]:',b[0])

a.shape: (4,)
a[0]: 1 

b.shape: (2, 3)
b[0,0]: 1
b[0]: [1 2 3]


In [19]:
a = np.zeros(2)     # zeros 함수 - 0이라는 값으로 채우는 함수 
print('a\n',a,"\n")

b = np.zeros((2,2))
print('b\n',b,"\n")

c = np.ones((2,3))   # 1로 채워지는 함수 
print('c\n',c,"\n")

d = np.full((2,3),5)   # 2행3열 만드는데 5로 채워라 
print('d\n',d,"\n")

e = np.eye(3)      # 3행 3열짜리 단위행렬을 만들어라
print('e\n',e,"\n")

a
 [0. 0.] 

b
 [[0. 0.]
 [0. 0.]] 

c
 [[1. 1. 1.]
 [1. 1. 1.]] 

d
 [[5 5 5]
 [5 5 5]] 

e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [7]:
# 실수형 배열 생성하기

a = np.array([1,2], dtype = np.float64)   # 실수형으로 배열 생성 64개 비트(8바이트) 사용하겠다
print(a.dtype)
print(a)              # 실수라서 소수점 들어감 

#  정수형 배열로 변환하기

a_i8 = a.astype(np.int8)      
print(a_i8.dtype)
print(a_i8)                      # 정수형이라 소수점 없음. 

float64
[1. 2.]
int8
[1 2]


In [21]:
arr = np.array([[0,1,2],[3,4,5]])
print(arr,"\n")

print('type(arr):', type(arr))
print('arr.ndim:' , arr.ndim,"\n")               # 'number of dimensions, ' 배열의 차원을 나타냄

print('arr.dtype:', arr.dtype)                      # 정수형태 32비트 
print('arr.itemsize:', arr.itemsize,"\n")    # 요소의 바이트 수     - 요소하나하나가 몇 바이트 

print('arr.size:', arr.size)                              # 요소의 개수
print('arr.nbytes:', arr.nbytes,"\n")          # 배열 전체 바이트 수 

print('arr.T:\n', arr.T)                                   # 행렬 치환
print('arr.shape:', arr.shape)


[[0 1 2]
 [3 4 5]] 

type(arr): <class 'numpy.ndarray'>
arr.ndim: 2 

arr.dtype: int32
arr.itemsize: 4 

arr.size: 6
arr.nbytes: 24 

arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)


In [26]:
#  1차원 배열 생성하기 

a = np.arange(8)
print('a\n', a,"\n")


#  다차원 배열로 변경하기 

a.shape = (2,4)
print('shape\n', a,"\n")


#  1차원 배열로 변경하기 

print('flatten\n', a.flatten(),"\n")


#  resize 함수로 모양  변경하기 
a.resize((4,2))      ## 튜플 형태로 입력 
print('resize\n', a)

a
 [0 1 2 3 4 5 6 7] 

shape
 [[0 1 2 3]
 [4 5 6 7]] 

flatten
 [0 1 2 3 4 5 6 7] 

resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [27]:
a = np.array([[0,1,2],[3,4,5]])
print('a\n',a)



a
 [[0 1 2]
 [3 4 5]]


In [28]:
##  마스킹 : 논리값  인덱싱

mask = np.array([0,1,1,0], dtype = bool)
print(mask)

data = np. random.randn(4,2)    ## 4행 2열 짜리 로 랜덤 값을 뽑아냄 
print("\ndata 출력 \n", data)

print('\n마스킹된 데이터 출력 \n', data[mask])                 ## true 값만 뽑아냄       행방향으로 0110  false true true false     false true true false   에서 true 자리값만 
print('\n마스킹 역전된 데이터 출력 \n', data[~mask])       ##  논리값 반대로 해서 true 값만 뽑아냄       

[False  True  True False]

data 출력 
 [[ 1.22708341  0.30990761]
 [-0.46164986  1.48365725]
 [ 1.42002572 -1.50195446]
 [ 0.54701751  0.62378626]]

마스킹된 데이터 출력 
 [[-0.46164986  1.48365725]
 [ 1.42002572 -1.50195446]]

마스킹 역전된 데이터 출력 
 [[1.22708341 0.30990761]
 [0.54701751 0.62378626]]


In [32]:
#  마스킹 : 조건식으로 마스킹 =============

posit = data[data > 0]
print('양수 데이터 출력' , '\n',posit,'\n')

# 다중 조건  =================

over1 = data[1][data[1]  > 0 ] 
print(' 두 번째 행의 양수 데이터 출력','\n',over1)


양수 데이터 출력 
 [1.22708341 0.30990761 1.48365725 1.42002572 0.54701751 0.62378626] 

 두 번째 행의 양수 데이터 출력 
 [1.48365725]


In [38]:
x = 100
y=x
print(y, '\n')

y=200
print(x)
print(y, '\n')

a = np.arange(6)      # 넘파이 어레이 형태로 배열 형태  (6개 ) 만들어져서 넣음
b = a                          # b는 집이 좁으니 주소값을 넘겨줌. 

print(a)
print(b)                     # 주소값을 따라가서 나온 값을 출력   - 하나를 둘이 쓰는 형태
print(b is a , '\n')

b[0] = 10       # 주소를 따라가서 [0] 번 인덱스에 10 대입 
print(a)

100 

100
200 

[0 1 2 3 4 5]
[0 1 2 3 4 5]
True 

[10  1  2  3  4  5]


In [40]:
a = np.arange(6)
c = a.copy()            # 배열이면 똑같이  공간을 늘려서 만들어서 넣음. 
print('A: ' , a)
print('C: ' , c, '\n')


c[0] = 20
print('A: ' , a)
print('C: ' , c)

A:  [0 1 2 3 4 5]
C:  [0 1 2 3 4 5] 

A:  [0 1 2 3 4 5]
C:  [20  1  2  3  4  5]


In [46]:
a = np.array([3,2,5,1,4])

print('원본\n', a,'\n')

print('정렬 후 \n', np.sort(a),'\n')      ## 배열 a는 원본 유지, a.sort(): 원본이 정렬상태로 변경

print('원본\n', a,'\n')                  # 원본은 그대로 

print('정렬한 인덱스 \n', np.argsort(a),'\n')   ##정렬되었을때, 각 값의 원래 인덱스 반환 

a.sort()
print('정렬 후 \n', a)                   # 원본이 정렬되어 바뀜 


원본
 [3 2 5 1 4] 

정렬 후 
 [1 2 3 4 5] 

원본
 [3 2 5 1 4] 

정렬한 인덱스 
 [3 1 0 4 2] 

정렬 후 
 [1 2 3 4 5]
